variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
- test

unit test:
  stage: test
  image: python:3.9.13-slim-buster
  before_script:
    - python3.9  -m venv .env
    - source .env/bin/activate
    - pip3 install -r requirements.txt
  script:
    -  nosetests -v --with-xunit --xunit-file=report.xml        
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 weeks

sast:
  stage: test
  variables:
    SAST_BANDIT_EXCLUDED_PATHS: '*/tests/*, */venv/*'
  artifacts:
    reports:
      sast: gl-sast-report.json


include:
- template: Security/SAST.gitlab-ci.yml
