variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

stages:
- test

unit test:
  stage: test
  image: python:3.9.13-slim-buster
  before_script:
    - python3.9  -m venv .env
    - source .env/bin/activate
    - pip3 install -r requirements.txt
  script:
    -  nosetests -v --with-xunit --xunit-file=report.xml        
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 2 weeks
  
test coverage:
  stage: test
  image: python:3.9.13-slim-buster
  before_script:
    - python3.9  -m venv .env
    - source .env/bin/activate
    - pip3 install -r requirements.txt
  script:
    - pip install pytest pytest-cov
    - coverage run -m pytest
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:    
    paths: [coverage.xml]
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml

sast:
  stage: test
  variables:
    SAST_BANDIT_EXCLUDED_PATHS: '*/tests/*, */venv/*'
  artifacts:    
    paths: [gl-sast-report.json]
    reports:
      sast: gl-sast-report.json

code_quality:
  image: docker:19.03.11
  artifacts:
    paths: [gl-code-quality-report.html]
    reports:
      codequality: gl-code-quality-report.json

include:
- template: Security/SAST.gitlab-ci.yml
- template: Code-Quality.gitlab-ci.yml
